apiVersion: apps/v1
kind: Deployment
metadata:
  name: bobgen-status
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bobgen-status
  template:
    metadata:
      labels:
        app: bobgen-status
    spec:
      containers:
      - name: bobgen-status
        image: bobgen-status:latest
        ports:
        - containerPort: 3000
