apiVersion: apps/v1
kind: Deployment
metadata:
  name: jokegen-deployment
  namespace: jokegen
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jokegen
  template:
    metadata:
      labels:
        app: jokegen
    spec:
      containers:
      - name: jokegen
        image: REPLACE_IMAGE
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
